// <auto-generated/>
// Emik.SourceGenerators.Tattoo, v2.0.7
#pragma warning disable
global using global::System;
global using global::System.Buffers;
global using global::System.Buffers.Binary;
global using global::System.Buffers.Text;
global using global::System.CodeDom;
global using global::System.CodeDom.Compiler;
global using global::System.Collections;
global using global::System.Collections.Concurrent;
global using global::System.Collections.Generic;
global using global::System.Collections.ObjectModel;
global using global::System.Collections.Specialized;
global using global::System.ComponentModel;
global using global::System.ComponentModel.Design;
global using global::System.ComponentModel.Design.Serialization;
global using global::System.Configuration;
global using global::System.Configuration.Assemblies;
global using global::System.Data;
global using global::System.Data.Common;
global using global::System.Data.SqlTypes;
global using global::System.Diagnostics;
global using global::System.Diagnostics.CodeAnalysis;
global using global::System.Diagnostics.Contracts;
global using global::System.Diagnostics.SymbolStore;
global using global::System.Diagnostics.Tracing;
global using global::System.Drawing;
global using global::System.Dynamic;
global using global::System.Globalization;
global using global::System.IO;
global using global::System.IO.Compression;
global using global::System.IO.IsolatedStorage;
global using global::System.IO.MemoryMappedFiles;
global using global::System.IO.Pipes;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Net;
global using global::System.Net.Cache;
global using global::System.Net.Http;
global using global::System.Net.Http.Headers;
global using global::System.Net.Mail;
global using global::System.Net.Mime;
global using global::System.Net.NetworkInformation;
global using global::System.Net.Security;
global using global::System.Net.Sockets;
global using global::System.Net.WebSockets;
global using global::System.Numerics;
global using global::System.Numerics.Hashing;
global using global::System.Reflection;
global using global::System.Reflection.Emit;
global using global::System.Resources;
global using global::System.Runtime;
global using global::System.Runtime.CompilerServices;
global using global::System.Runtime.ConstrainedExecution;
global using global::System.Runtime.ExceptionServices;
global using global::System.Runtime.InteropServices;
global using global::System.Runtime.InteropServices.ComTypes;
global using global::System.Runtime.Serialization;
global using global::System.Runtime.Serialization.Formatters;
global using global::System.Runtime.Serialization.Formatters.Binary;
global using global::System.Runtime.Serialization.Json;
global using global::System.Runtime.Versioning;
global using global::System.Security;
global using global::System.Security.AccessControl;
global using global::System.Security.Authentication;
global using global::System.Security.Authentication.ExtendedProtection;
global using global::System.Security.Claims;
global using global::System.Security.Cryptography;
global using global::System.Security.Cryptography.X509Certificates;
global using global::System.Security.Permissions;
global using global::System.Security.Principal;
global using global::System.Text;
global using global::System.Text.RegularExpressions;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::System.Threading.Tasks.Sources;
global using global::System.Timers;
global using global::System.Transactions;
global using global::System.Web;
global using global::System.Windows;
global using global::System.Windows.Input;
global using global::System.Xml;
global using global::System.Xml.Linq;
global using global::System.Xml.Resolvers;
global using global::System.Xml.Schema;
global using global::System.Xml.Serialization;
global using global::System.Xml.XPath;
global using global::System.Xml.Xsl;
global using global::CommunityToolkit;
global using global::CommunityToolkit.Common;
global using global::CommunityToolkit.Common.Collections;
global using global::CommunityToolkit.Common.Deferred;
global using global::CommunityToolkit.Common.Extensions;
global using global::CommunityToolkit.Common.Helpers;
global using global::CommunityToolkit.Diagnostics;
global using global::CommunityToolkit.Helpers;
global using global::CommunityToolkit.HighPerformance;
global using global::CommunityToolkit.HighPerformance.Buffers;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces;
global using global::CommunityToolkit.HighPerformance.Buffers.Views;
global using global::CommunityToolkit.HighPerformance.Enumerables;
global using global::CommunityToolkit.HighPerformance.Helpers;
global using global::CommunityToolkit.HighPerformance.Helpers.Internals;
global using global::CommunityToolkit.HighPerformance.Memory;
global using global::CommunityToolkit.HighPerformance.Memory.Internals;
global using global::CommunityToolkit.HighPerformance.Memory.Views;
global using global::CommunityToolkit.HighPerformance.Streams;
global using global::Emik;
global using global::FxResources;
global using global::FxResources.Microsoft;
global using global::FxResources.Microsoft.Bcl;
global using global::FxResources.Microsoft.Bcl.HashCode;
global using global::FxResources.System;
global using global::FxResources.System.Buffers;
global using global::FxResources.System.Memory;
global using global::FxResources.System.Numerics;
global using global::FxResources.System.Numerics.Vectors;
global using global::ILMerge;
global using global::InlineIL;
global using global::InlineMethod;
global using global::JetBrains;
global using global::JetBrains.Annotations;
global using global::LocalsInit;
global using global::Microsoft;
global using global::Microsoft.CSharp;
global using global::Microsoft.CodeAnalysis;
global using global::Microsoft.VisualBasic;
global using global::Microsoft.Win32;
global using global::Microsoft.Win32.SafeHandles;
global using global::NullGuard;
global using global::NullGuard.CodeAnalysis;

// Polyfills of namespaces in case dependencies are conditional.
namespace System { }

namespace System.Buffers { }

namespace System.Buffers.Binary { }

namespace System.Buffers.Text { }

namespace System.CodeDom { }

namespace System.CodeDom.Compiler { }

namespace System.Collections { }

namespace System.Collections.Concurrent { }

namespace System.Collections.Generic { }

namespace System.Collections.ObjectModel { }

namespace System.Collections.Specialized { }

namespace System.ComponentModel { }

namespace System.ComponentModel.Design { }

namespace System.ComponentModel.Design.Serialization { }

namespace System.Configuration { }

namespace System.Configuration.Assemblies { }

namespace System.Data { }

namespace System.Data.Common { }

namespace System.Data.SqlTypes { }

namespace System.Diagnostics { }

namespace System.Diagnostics.CodeAnalysis { }

namespace System.Diagnostics.Contracts { }

namespace System.Diagnostics.SymbolStore { }

namespace System.Diagnostics.Tracing { }

namespace System.Drawing { }

namespace System.Dynamic { }

namespace System.Globalization { }

namespace System.IO { }

namespace System.IO.Compression { }

namespace System.IO.IsolatedStorage { }

namespace System.IO.MemoryMappedFiles { }

namespace System.IO.Pipes { }

namespace System.Linq { }

namespace System.Linq.Expressions { }

namespace System.Net { }

namespace System.Net.Cache { }

namespace System.Net.Http { }

namespace System.Net.Http.Headers { }

namespace System.Net.Mail { }

namespace System.Net.Mime { }

namespace System.Net.NetworkInformation { }

namespace System.Net.Security { }

namespace System.Net.Sockets { }

namespace System.Net.WebSockets { }

namespace System.Numerics { }

namespace System.Numerics.Hashing { }

namespace System.Reflection { }

namespace System.Reflection.Emit { }

namespace System.Resources { }

namespace System.Runtime { }

namespace System.Runtime.CompilerServices { }

namespace System.Runtime.ConstrainedExecution { }

namespace System.Runtime.ExceptionServices { }

namespace System.Runtime.InteropServices { }

namespace System.Runtime.InteropServices.ComTypes { }

namespace System.Runtime.Serialization { }

namespace System.Runtime.Serialization.Formatters { }

namespace System.Runtime.Serialization.Formatters.Binary { }

namespace System.Runtime.Serialization.Json { }

namespace System.Runtime.Versioning { }

namespace System.Security { }

namespace System.Security.AccessControl { }

namespace System.Security.Authentication { }

namespace System.Security.Authentication.ExtendedProtection { }

namespace System.Security.Claims { }

namespace System.Security.Cryptography { }

namespace System.Security.Cryptography.X509Certificates { }

namespace System.Security.Permissions { }

namespace System.Security.Principal { }

namespace System.Text { }

namespace System.Text.RegularExpressions { }

namespace System.Threading { }

namespace System.Threading.Tasks { }

namespace System.Threading.Tasks.Sources { }

namespace System.Timers { }

namespace System.Transactions { }

namespace System.Web { }

namespace System.Windows { }

namespace System.Windows.Input { }

namespace System.Xml { }

namespace System.Xml.Linq { }

namespace System.Xml.Resolvers { }

namespace System.Xml.Schema { }

namespace System.Xml.Serialization { }

namespace System.Xml.XPath { }

namespace System.Xml.Xsl { }

namespace CommunityToolkit { }

namespace CommunityToolkit.Common { }

namespace CommunityToolkit.Common.Collections { }

namespace CommunityToolkit.Common.Deferred { }

namespace CommunityToolkit.Common.Extensions { }

namespace CommunityToolkit.Common.Helpers { }

namespace CommunityToolkit.Diagnostics { }

namespace CommunityToolkit.Helpers { }

namespace CommunityToolkit.HighPerformance { }

namespace CommunityToolkit.HighPerformance.Buffers { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces { }

namespace CommunityToolkit.HighPerformance.Buffers.Views { }

namespace CommunityToolkit.HighPerformance.Enumerables { }

namespace CommunityToolkit.HighPerformance.Helpers { }

namespace CommunityToolkit.HighPerformance.Helpers.Internals { }

namespace CommunityToolkit.HighPerformance.Memory { }

namespace CommunityToolkit.HighPerformance.Memory.Internals { }

namespace CommunityToolkit.HighPerformance.Memory.Views { }

namespace CommunityToolkit.HighPerformance.Streams { }

namespace Emik { }

namespace FxResources { }

namespace FxResources.Microsoft { }

namespace FxResources.Microsoft.Bcl { }

namespace FxResources.Microsoft.Bcl.HashCode { }

namespace FxResources.System { }

namespace FxResources.System.Buffers { }

namespace FxResources.System.Memory { }

namespace FxResources.System.Numerics { }

namespace FxResources.System.Numerics.Vectors { }

namespace ILMerge { }

namespace InlineIL { }

namespace InlineMethod { }

namespace JetBrains { }

namespace JetBrains.Annotations { }

namespace LocalsInit { }

namespace Microsoft { }

namespace Microsoft.CSharp { }

namespace Microsoft.CodeAnalysis { }

namespace Microsoft.VisualBasic { }

namespace Microsoft.Win32 { }

namespace Microsoft.Win32.SafeHandles { }

namespace NullGuard { }

namespace NullGuard.CodeAnalysis { }
