// <auto-generated/>
// Emik.SourceGenerators.Tattoo, v2.0.2
#pragma warning disable
global using global::System;
global using global::System.Buffers;
global using global::System.Buffers.Binary;
global using global::System.Buffers.Text;
global using global::System.CodeDom;
global using global::System.CodeDom.Compiler;
global using global::System.Collections;
global using global::System.Collections.Concurrent;
global using global::System.Collections.Generic;
global using global::System.Collections.Immutable;
global using global::System.Collections.ObjectModel;
global using global::System.Collections.Specialized;
global using global::System.ComponentModel;
global using global::System.ComponentModel.Design;
global using global::System.ComponentModel.Design.Serialization;
global using global::System.Configuration;
global using global::System.Configuration.Assemblies;
global using global::System.Data;
global using global::System.Data.Common;
global using global::System.Data.SqlTypes;
global using global::System.Diagnostics;
global using global::System.Diagnostics.CodeAnalysis;
global using global::System.Diagnostics.Contracts;
global using global::System.Diagnostics.SymbolStore;
global using global::System.Diagnostics.Tracing;
global using global::System.Drawing;
global using global::System.Dynamic;
global using global::System.Globalization;
global using global::System.IO;
global using global::System.IO.Compression;
global using global::System.IO.IsolatedStorage;
global using global::System.IO.MemoryMappedFiles;
global using global::System.IO.Pipes;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Net;
global using global::System.Net.Cache;
global using global::System.Net.Http;
global using global::System.Net.Http.Headers;
global using global::System.Net.Mail;
global using global::System.Net.Mime;
global using global::System.Net.NetworkInformation;
global using global::System.Net.Security;
global using global::System.Net.Sockets;
global using global::System.Net.WebSockets;
global using global::System.Numerics;
global using global::System.Numerics.Hashing;
global using global::System.Reflection;
global using global::System.Reflection.Emit;
global using global::System.Reflection.Internal;
global using global::System.Reflection.Metadata;
global using global::System.Reflection.Metadata.Ecma335;
global using global::System.Reflection.PortableExecutable;
global using global::System.Resources;
global using global::System.Runtime;
global using global::System.Runtime.CompilerServices;
global using global::System.Runtime.ConstrainedExecution;
global using global::System.Runtime.ExceptionServices;
global using global::System.Runtime.InteropServices;
global using global::System.Runtime.InteropServices.ComTypes;
global using global::System.Runtime.Serialization;
global using global::System.Runtime.Serialization.Formatters;
global using global::System.Runtime.Serialization.Formatters.Binary;
global using global::System.Runtime.Serialization.Json;
global using global::System.Runtime.Versioning;
global using global::System.Security;
global using global::System.Security.AccessControl;
global using global::System.Security.Authentication;
global using global::System.Security.Authentication.ExtendedProtection;
global using global::System.Security.Claims;
global using global::System.Security.Cryptography;
global using global::System.Security.Cryptography.X509Certificates;
global using global::System.Security.Permissions;
global using global::System.Security.Principal;
global using global::System.Text;
global using global::System.Text.RegularExpressions;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::System.Threading.Tasks.Sources;
global using global::System.Timers;
global using global::System.Transactions;
global using global::System.Web;
global using global::System.Windows;
global using global::System.Windows.Input;
global using global::System.Xml;
global using global::System.Xml.Linq;
global using global::System.Xml.Resolvers;
global using global::System.Xml.Schema;
global using global::System.Xml.Serialization;
global using global::System.Xml.XPath;
global using global::System.Xml.Xsl;
global using global::CommunityToolkit;
global using global::CommunityToolkit.Common;
global using global::CommunityToolkit.Common.Collections;
global using global::CommunityToolkit.Common.Deferred;
global using global::CommunityToolkit.Common.Extensions;
global using global::CommunityToolkit.Common.Helpers;
global using global::CommunityToolkit.Diagnostics;
global using global::CommunityToolkit.Helpers;
global using global::CommunityToolkit.HighPerformance;
global using global::CommunityToolkit.HighPerformance.Buffers;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces;
global using global::CommunityToolkit.HighPerformance.Buffers.Views;
global using global::CommunityToolkit.HighPerformance.Enumerables;
global using global::CommunityToolkit.HighPerformance.Helpers;
global using global::CommunityToolkit.HighPerformance.Helpers.Internals;
global using global::CommunityToolkit.HighPerformance.Memory;
global using global::CommunityToolkit.HighPerformance.Memory.Internals;
global using global::CommunityToolkit.HighPerformance.Memory.Views;
global using global::CommunityToolkit.HighPerformance.Streams;
global using global::DefaultDocumentation;
global using global::DefaultDocumentation.Api;
global using global::DefaultDocumentation.Markdown;
global using global::DefaultDocumentation.Markdown.Elements;
global using global::DefaultDocumentation.Markdown.Extensions;
global using global::DefaultDocumentation.Markdown.FileNameFactories;
global using global::DefaultDocumentation.Markdown.Internal;
global using global::DefaultDocumentation.Markdown.Sections;
global using global::DefaultDocumentation.Markdown.UrlFactories;
global using global::DefaultDocumentation.Markdown.Writers;
global using global::DefaultDocumentation.Models;
global using global::DefaultDocumentation.Models.Members;
global using global::DefaultDocumentation.Models.Parameters;
global using global::DefaultDocumentation.Models.Types;
global using global::Emik;
global using global::Emik.DefaultDocumentation;
global using global::Emik.Morsels;
global using global::Fody;
global using global::FxResources;
global using global::FxResources.System;
global using global::FxResources.System.Collections;
global using global::FxResources.System.Collections.Immutable;
global using global::FxResources.System.Memory;
global using global::FxResources.System.Reflection;
global using global::FxResources.System.Reflection.Metadata;
global using global::Humanizer;
global using global::Humanizer.Inflections;
global using global::ICSharpCode;
global using global::ICSharpCode.Decompiler;
global using global::ICSharpCode.Decompiler.CSharp;
global using global::ICSharpCode.Decompiler.CSharp.OutputVisitor;
global using global::ICSharpCode.Decompiler.CSharp.ProjectDecompiler;
global using global::ICSharpCode.Decompiler.CSharp.Resolver;
global using global::ICSharpCode.Decompiler.CSharp.Syntax;
global using global::ICSharpCode.Decompiler.CSharp.Syntax.PatternMatching;
global using global::ICSharpCode.Decompiler.CSharp.Transforms;
global using global::ICSharpCode.Decompiler.CSharp.TypeSystem;
global using global::ICSharpCode.Decompiler.DebugInfo;
global using global::ICSharpCode.Decompiler.Disassembler;
global using global::ICSharpCode.Decompiler.Documentation;
global using global::ICSharpCode.Decompiler.FlowAnalysis;
global using global::ICSharpCode.Decompiler.IL;
global using global::ICSharpCode.Decompiler.IL.ControlFlow;
global using global::ICSharpCode.Decompiler.IL.Patterns;
global using global::ICSharpCode.Decompiler.IL.Transforms;
global using global::ICSharpCode.Decompiler.Instrumentation;
global using global::ICSharpCode.Decompiler.Metadata;
global using global::ICSharpCode.Decompiler.Output;
global using global::ICSharpCode.Decompiler.Semantics;
global using global::ICSharpCode.Decompiler.Solution;
global using global::ICSharpCode.Decompiler.TypeSystem;
global using global::ICSharpCode.Decompiler.TypeSystem.Implementation;
global using global::ICSharpCode.Decompiler.Util;
global using global::ILMerge;
global using global::InlineIL;
global using global::InlineMethod;
global using global::JetBrains;
global using global::JetBrains.Annotations;
global using global::Lazy;
global using global::LightJson;
global using global::LightJson.Serialization;
global using global::LocalsInit;
global using global::Microsoft;
global using global::Microsoft.CSharp;
global using global::Microsoft.CodeAnalysis;
global using global::Microsoft.VisualBasic;
global using global::Microsoft.Win32;
global using global::Microsoft.Win32.SafeHandles;
global using global::NLog;
global using global::NLog.Attributes;
global using global::NLog.Common;
global using global::NLog.Conditions;
global using global::NLog.Config;
global using global::NLog.Filters;
global using global::NLog.Fluent;
global using global::NLog.Internal;
global using global::NLog.Internal.Fakeables;
global using global::NLog.Internal.FileAppenders;
global using global::NLog.Internal.NetworkSenders;
global using global::NLog.Internal.Xamarin;
global using global::NLog.LayoutRenderers;
global using global::NLog.LayoutRenderers.Wrappers;
global using global::NLog.Layouts;
global using global::NLog.MessageTemplates;
global using global::NLog.Targets;
global using global::NLog.Targets.FileArchiveModes;
global using global::NLog.Targets.Wrappers;
global using global::NLog.Time;
global using global::Newtonsoft;
global using global::Newtonsoft.Json;
global using global::Newtonsoft.Json.Bson;
global using global::Newtonsoft.Json.Converters;
global using global::Newtonsoft.Json.Linq;
global using global::Newtonsoft.Json.Linq.JsonPath;
global using global::Newtonsoft.Json.Schema;
global using global::Newtonsoft.Json.Serialization;
global using global::Newtonsoft.Json.Utilities;
global using global::NullGuard;
global using global::NullGuard.CodeAnalysis;
global using global::Scifa;
global using global::Scifa.CheckedExceptions;
global using global::Scifa.CheckedExceptions.Attributes;
global using global::Substitute;
global using global::Virtuosity;

// Polyfills of namespaces in case dependencies are conditional.
namespace System { }

namespace System.Buffers { }

namespace System.Buffers.Binary { }

namespace System.Buffers.Text { }

namespace System.CodeDom { }

namespace System.CodeDom.Compiler { }

namespace System.Collections { }

namespace System.Collections.Concurrent { }

namespace System.Collections.Generic { }

namespace System.Collections.Immutable { }

namespace System.Collections.ObjectModel { }

namespace System.Collections.Specialized { }

namespace System.ComponentModel { }

namespace System.ComponentModel.Design { }

namespace System.ComponentModel.Design.Serialization { }

namespace System.Configuration { }

namespace System.Configuration.Assemblies { }

namespace System.Data { }

namespace System.Data.Common { }

namespace System.Data.SqlTypes { }

namespace System.Diagnostics { }

namespace System.Diagnostics.CodeAnalysis { }

namespace System.Diagnostics.Contracts { }

namespace System.Diagnostics.SymbolStore { }

namespace System.Diagnostics.Tracing { }

namespace System.Drawing { }

namespace System.Dynamic { }

namespace System.Globalization { }

namespace System.IO { }

namespace System.IO.Compression { }

namespace System.IO.IsolatedStorage { }

namespace System.IO.MemoryMappedFiles { }

namespace System.IO.Pipes { }

namespace System.Linq { }

namespace System.Linq.Expressions { }

namespace System.Net { }

namespace System.Net.Cache { }

namespace System.Net.Http { }

namespace System.Net.Http.Headers { }

namespace System.Net.Mail { }

namespace System.Net.Mime { }

namespace System.Net.NetworkInformation { }

namespace System.Net.Security { }

namespace System.Net.Sockets { }

namespace System.Net.WebSockets { }

namespace System.Numerics { }

namespace System.Numerics.Hashing { }

namespace System.Reflection { }

namespace System.Reflection.Emit { }

namespace System.Reflection.Internal { }

namespace System.Reflection.Metadata { }

namespace System.Reflection.Metadata.Ecma335 { }

namespace System.Reflection.PortableExecutable { }

namespace System.Resources { }

namespace System.Runtime { }

namespace System.Runtime.CompilerServices { }

namespace System.Runtime.ConstrainedExecution { }

namespace System.Runtime.ExceptionServices { }

namespace System.Runtime.InteropServices { }

namespace System.Runtime.InteropServices.ComTypes { }

namespace System.Runtime.Serialization { }

namespace System.Runtime.Serialization.Formatters { }

namespace System.Runtime.Serialization.Formatters.Binary { }

namespace System.Runtime.Serialization.Json { }

namespace System.Runtime.Versioning { }

namespace System.Security { }

namespace System.Security.AccessControl { }

namespace System.Security.Authentication { }

namespace System.Security.Authentication.ExtendedProtection { }

namespace System.Security.Claims { }

namespace System.Security.Cryptography { }

namespace System.Security.Cryptography.X509Certificates { }

namespace System.Security.Permissions { }

namespace System.Security.Principal { }

namespace System.Text { }

namespace System.Text.RegularExpressions { }

namespace System.Threading { }

namespace System.Threading.Tasks { }

namespace System.Threading.Tasks.Sources { }

namespace System.Timers { }

namespace System.Transactions { }

namespace System.Web { }

namespace System.Windows { }

namespace System.Windows.Input { }

namespace System.Xml { }

namespace System.Xml.Linq { }

namespace System.Xml.Resolvers { }

namespace System.Xml.Schema { }

namespace System.Xml.Serialization { }

namespace System.Xml.XPath { }

namespace System.Xml.Xsl { }

namespace CommunityToolkit { }

namespace CommunityToolkit.Common { }

namespace CommunityToolkit.Common.Collections { }

namespace CommunityToolkit.Common.Deferred { }

namespace CommunityToolkit.Common.Extensions { }

namespace CommunityToolkit.Common.Helpers { }

namespace CommunityToolkit.Diagnostics { }

namespace CommunityToolkit.Helpers { }

namespace CommunityToolkit.HighPerformance { }

namespace CommunityToolkit.HighPerformance.Buffers { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces { }

namespace CommunityToolkit.HighPerformance.Buffers.Views { }

namespace CommunityToolkit.HighPerformance.Enumerables { }

namespace CommunityToolkit.HighPerformance.Helpers { }

namespace CommunityToolkit.HighPerformance.Helpers.Internals { }

namespace CommunityToolkit.HighPerformance.Memory { }

namespace CommunityToolkit.HighPerformance.Memory.Internals { }

namespace CommunityToolkit.HighPerformance.Memory.Views { }

namespace CommunityToolkit.HighPerformance.Streams { }

namespace DefaultDocumentation { }

namespace DefaultDocumentation.Api { }

namespace DefaultDocumentation.Markdown { }

namespace DefaultDocumentation.Markdown.Elements { }

namespace DefaultDocumentation.Markdown.Extensions { }

namespace DefaultDocumentation.Markdown.FileNameFactories { }

namespace DefaultDocumentation.Markdown.Internal { }

namespace DefaultDocumentation.Markdown.Sections { }

namespace DefaultDocumentation.Markdown.UrlFactories { }

namespace DefaultDocumentation.Markdown.Writers { }

namespace DefaultDocumentation.Models { }

namespace DefaultDocumentation.Models.Members { }

namespace DefaultDocumentation.Models.Parameters { }

namespace DefaultDocumentation.Models.Types { }

namespace Emik { }

namespace Emik.DefaultDocumentation { }

namespace Emik.Morsels { }

namespace Fody { }

namespace FxResources { }

namespace FxResources.System { }

namespace FxResources.System.Collections { }

namespace FxResources.System.Collections.Immutable { }

namespace FxResources.System.Memory { }

namespace FxResources.System.Reflection { }

namespace FxResources.System.Reflection.Metadata { }

namespace Humanizer { }

namespace Humanizer.Inflections { }

namespace ICSharpCode { }

namespace ICSharpCode.Decompiler { }

namespace ICSharpCode.Decompiler.CSharp { }

namespace ICSharpCode.Decompiler.CSharp.OutputVisitor { }

namespace ICSharpCode.Decompiler.CSharp.ProjectDecompiler { }

namespace ICSharpCode.Decompiler.CSharp.Resolver { }

namespace ICSharpCode.Decompiler.CSharp.Syntax { }

namespace ICSharpCode.Decompiler.CSharp.Syntax.PatternMatching { }

namespace ICSharpCode.Decompiler.CSharp.Transforms { }

namespace ICSharpCode.Decompiler.CSharp.TypeSystem { }

namespace ICSharpCode.Decompiler.DebugInfo { }

namespace ICSharpCode.Decompiler.Disassembler { }

namespace ICSharpCode.Decompiler.Documentation { }

namespace ICSharpCode.Decompiler.FlowAnalysis { }

namespace ICSharpCode.Decompiler.IL { }

namespace ICSharpCode.Decompiler.IL.ControlFlow { }

namespace ICSharpCode.Decompiler.IL.Patterns { }

namespace ICSharpCode.Decompiler.IL.Transforms { }

namespace ICSharpCode.Decompiler.Instrumentation { }

namespace ICSharpCode.Decompiler.Metadata { }

namespace ICSharpCode.Decompiler.Output { }

namespace ICSharpCode.Decompiler.Semantics { }

namespace ICSharpCode.Decompiler.Solution { }

namespace ICSharpCode.Decompiler.TypeSystem { }

namespace ICSharpCode.Decompiler.TypeSystem.Implementation { }

namespace ICSharpCode.Decompiler.Util { }

namespace ILMerge { }

namespace InlineIL { }

namespace InlineMethod { }

namespace JetBrains { }

namespace JetBrains.Annotations { }

namespace Lazy { }

namespace LightJson { }

namespace LightJson.Serialization { }

namespace LocalsInit { }

namespace Microsoft { }

namespace Microsoft.CSharp { }

namespace Microsoft.CodeAnalysis { }

namespace Microsoft.VisualBasic { }

namespace Microsoft.Win32 { }

namespace Microsoft.Win32.SafeHandles { }

namespace NLog { }

namespace NLog.Attributes { }

namespace NLog.Common { }

namespace NLog.Conditions { }

namespace NLog.Config { }

namespace NLog.Filters { }

namespace NLog.Fluent { }

namespace NLog.Internal { }

namespace NLog.Internal.Fakeables { }

namespace NLog.Internal.FileAppenders { }

namespace NLog.Internal.NetworkSenders { }

namespace NLog.Internal.Xamarin { }

namespace NLog.LayoutRenderers { }

namespace NLog.LayoutRenderers.Wrappers { }

namespace NLog.Layouts { }

namespace NLog.MessageTemplates { }

namespace NLog.Targets { }

namespace NLog.Targets.FileArchiveModes { }

namespace NLog.Targets.Wrappers { }

namespace NLog.Time { }

namespace Newtonsoft { }

namespace Newtonsoft.Json { }

namespace Newtonsoft.Json.Bson { }

namespace Newtonsoft.Json.Converters { }

namespace Newtonsoft.Json.Linq { }

namespace Newtonsoft.Json.Linq.JsonPath { }

namespace Newtonsoft.Json.Schema { }

namespace Newtonsoft.Json.Serialization { }

namespace Newtonsoft.Json.Utilities { }

namespace NullGuard { }

namespace NullGuard.CodeAnalysis { }

namespace Scifa { }

namespace Scifa.CheckedExceptions { }

namespace Scifa.CheckedExceptions.Attributes { }

namespace Substitute { }

namespace Virtuosity { }
